server {
    listen 80;
    server_name _;

    # Frontend
    location / {
        root /home/rene_abraham_calzadilla_calderon/AERSA-TALOS-PROJECT/talos-server/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # RAG API
    location /api/rag/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Reports API
    location /api/reports/ {
        proxy_pass http://localhost:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
