server {
    if ($host = www.pejelagartopiloto.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = pejelagartopiloto.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name pejelagartopiloto.site www.pejelagartopiloto.site;
    return 301 https://$host$request_uri;




}

server {
    listen 443 ssl;
    server_name pejelagartopiloto.site www.pejelagartopiloto.site;
    ssl_certificate /etc/letsencrypt/live/pejelagartopiloto.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pejelagartopiloto.site/privkey.pem; # managed by Certbot


    location / {
        root /home/rene_abraham_calzadilla_calderon/AERSA-TALOS-PROJECT/talos-server/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/rag/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, X-API-Key";
        if ($request_method = OPTIONS) {
            return 204;
        }
    }

    location /api/reports/ {
        proxy_pass http://localhost:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, X-API-Key";
        if ($request_method = OPTIONS) {
            return 204;
        }
    }


}
